# Generated by Django 5.0.1 on 2024-02-17 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movielist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielist',
            old_name='models',
            new_name='movie',
        ),
    ]
